install:
	./gradlew installDist

run-app:
	./build/install/app/bin/app

lint:
	./gradlew checkstyleMain

test:
	./gradlew test

build:
	./gradlew build

report:
	./gradlew jacocoTestReport

.PHONY: build